// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViewGrid.Infrastructure.Persistence;

#nullable disable

namespace ViewGrid.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ViewGridDbContext))]
    [Migration("20260510171458_AddRegionTransformColumns")]
    partial class AddRegionTransformColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ViewGrid.Core.Entities.GridCanvas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColLocked")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("col_locked");

                    b.Property<string>("ColWeights")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("col_weights");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GridCols")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RowLocked")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("row_locked");

                    b.Property<string>("RowWeights")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("row_weights");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CanvasSize", "ViewGrid.Core.Entities.GridCanvas.CanvasSize#PixelSize", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("canvas_height");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("canvas_width");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("grid_canvases", (string)null);
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.GridPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CopyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GridId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PixelOffsetX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PixelOffsetY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlacementOrder")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OccupySize", "ViewGrid.Core.Entities.GridPlacement.OccupySize#OccupySize", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("occupy_height");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("occupy_width");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "ViewGrid.Core.Entities.GridPlacement.Position#CellPosition", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER")
                                .HasColumnName("grid_x");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER")
                                .HasColumnName("grid_y");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CopyId");

                    b.HasIndex("GridId");

                    b.HasIndex("GridId", "PlacementOrder");

                    b.ToTable("grid_placements", (string)null);
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.ImageAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredRelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Size", "ViewGrid.Core.Entities.ImageAsset.Size#PixelSize", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("height");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("width");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.ToTable("image_assets", (string)null);
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.ImageCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AutoCropTargetColor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_crop_color");

                    b.Property<int?>("AutoCropThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_crop_threshold");

                    b.Property<string>("CopyName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ManualCropHeight")
                        .HasColumnType("REAL")
                        .HasColumnName("manual_crop_height");

                    b.Property<double?>("ManualCropWidth")
                        .HasColumnType("REAL")
                        .HasColumnName("manual_crop_width");

                    b.Property<double?>("ManualCropX")
                        .HasColumnType("REAL")
                        .HasColumnName("manual_crop_x");

                    b.Property<double?>("ManualCropY")
                        .HasColumnType("REAL")
                        .HasColumnName("manual_crop_y");

                    b.Property<string>("ScalingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("scaling_mode");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Alignment", "ViewGrid.Core.Entities.ImageCopy.Alignment#Alignment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("X")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("align_x");

                            b1.Property<string>("Y")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("align_y");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OccupySize", "ViewGrid.Core.Entities.ImageCopy.OccupySize#OccupySize", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("occupy_height");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("occupy_width");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Transform", "ViewGrid.Core.Entities.ImageCopy.Transform#ImageTransform", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("FlipX")
                                .HasColumnType("INTEGER")
                                .HasColumnName("flip_x");

                            b1.Property<bool>("FlipY")
                                .HasColumnType("INTEGER")
                                .HasColumnName("flip_y");

                            b1.Property<int>("Rotation")
                                .HasColumnType("INTEGER")
                                .HasColumnName("rotation");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("image_copies", (string)null);
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.ProtectedRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("FillColor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fill_color");

                    b.Property<int>("FillMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fill_mode");

                    b.Property<bool>("FlipX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("region_flip_x");

                    b.Property<bool>("FlipY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("region_flip_y");

                    b.Property<Guid>("ImageCopyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OffsetXPx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("offset_x_px");

                    b.Property<int>("OffsetYPx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("offset_y_px");

                    b.Property<int>("Rotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("region_rotation");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Rect", "ViewGrid.Core.Entities.ProtectedRegion.Rect#RegionRectFraction", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .HasColumnType("REAL")
                                .HasColumnName("rect_height");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL")
                                .HasColumnName("rect_width");

                            b1.Property<double>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("rect_x");

                            b1.Property<double>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("rect_y");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ImageCopyId");

                    b.HasIndex("ImageCopyId", "SortOrder");

                    b.ToTable("image_copy_regions", (string)null);
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.GridPlacement", b =>
                {
                    b.HasOne("ViewGrid.Core.Entities.ImageCopy", null)
                        .WithMany()
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViewGrid.Core.Entities.GridCanvas", null)
                        .WithMany()
                        .HasForeignKey("GridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.ImageCopy", b =>
                {
                    b.HasOne("ViewGrid.Core.Entities.ImageAsset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ViewGrid.Core.Entities.ProtectedRegion", b =>
                {
                    b.HasOne("ViewGrid.Core.Entities.ImageCopy", null)
                        .WithMany()
                        .HasForeignKey("ImageCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
